// <auto-generated />
namespace CareerTracker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class migrateToClaims : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migrateToClaims));
        
        string IMigrationMetadata.Id
        {
            get { return "201602112119390_migrateToClaims"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
