// <auto-generated />
namespace CareerTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class urlToLocation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(urlToLocation));
        
        string IMigrationMetadata.Id
        {
            get { return "201602022125556_urlToLocation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
