// <auto-generated />
namespace CareerTracker.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class addedActiveFlag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedActiveFlag));
        
        string IMigrationMetadata.Id
        {
            get { return "201601282118208_addedActiveFlag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
